config/routes.rb
Rails.application.routes.draw do
  
  resources :products
  resources :payments
  resources :invoices

  devise_for :users
  resources :users
  root to: 'visitors#index'
  resources :customers
  resources :quickbooks do
    collection do
      get :authenticate
      get :oauth_callback
      get :disconnect
    end
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :customer
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  
  belongs_to :user
  
  has_one :shipping_address, class_name: 'Address', dependent: :destroy
  has_one :billing_address, class_name: 'Address', dependent: :destroy
  
  has_many :invoices, dependent: :destroy
  has_many :payments, dependent: :destroy
  
  accepts_nested_attributes_for :shipping_address, allow_destroy: true
  accepts_nested_attributes_for :billing_address, allow_destroy: true
  accepts_nested_attributes_for :payments, allow_destroy: true
  accepts_nested_attributes_for :invoices, allow_destroy: true
  
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  
  belongs_to :customer
  
  has_many :payments
  has_many :sales_line_item_detail, dependent: :destroy
  has_many :products, through: :sales_line_item_details
  
  has_one :transacion, as: :transactionable
  has_one :sub_total_line_item_detail, dependent: :destroy
  has_one :tax_line_item_detail, dependent: :destroy
  has_one :discount_line_item_detail, dependent: :destroy
  
  accepts_nested_attributes_for :sales_line_item_detail, allow_destroy: true
  accepts_nested_attributes_for :sub_total_line_item_detail, allow_destroy: true
  accepts_nested_attributes_for :tax_line_item_detail, allow_destroy: true
  accepts_nested_attributes_for :discount_line_item_detail, allow_destroy: true
  
  before_update :update_attributes
  before_save :update_attributes
  after_save :update_attributes
  after_update :update_attributes
  after_initialize :update_attributes
  
  def update_attributes
    t_price = tot_price - discount_price
   # t_price - () (tax_precent * t_price)
  end
  
  def tot_price
    sales_line_item_detail.to_a.sum(&:total_price) 
  end
  
  def tax_precent
    tax_line_item_detail.tax_precent / 100
  end
  
  def discount_percent
    discount_line_item_detail.discount_percentage / 100
  end
  
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  has_one :transacion, as: :transactionable
  belongs_to :invoice
  belongs_to :customer  
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_category
  
  has_many :sales_line_item_details
  has_many :invoices, through: :sales_line_item_details
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  has_many :products
end

app/models/sales_line_item_detail.rb
class SalesLineItemDetail < ActiveRecord::Base
  belongs_to :product
  belongs_to :invoice
end

app/models/tax_line_item_detail.rb
class TaxLineItemDetail < ActiveRecord::Base
  belongs_to :invoice
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :transactionable, polymorphic: true
  belongs_to :user
  belongs_to :transaction_category
end

app/models/transaction_category.rb
class TransactionCategory < ActiveRecord::Base
  has_many :transactions
  accepts_nested_attributes_for :transactions, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :customers
  has_many :transactions
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable
  
  def self.find_for_open_id(access_token, signed_in_resource=nil)
    data = access_token.info
    if user = User.where(:email => data["email"]).first
      user
    else
      User.create!(:email => data["email"], :password => Devise.friendly_token[0,20])
    end
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def new
  end

  def edit
  end

  def create
  end

  def destroy
  end
end

app/controllers/modal_responder.rb
class ModalResponder < ActionController::Responder
  cattr_accessor :modal_layout
  self.modal_layout = 'modal'

  def render(*args)
    options = args.extract_options!
    if request.xhr?
      options.merge! layout: modal_layout
    end
    controller.render *args, options
  end

  def default_render(*args)
    render(*args)
  end

  def redirect_to(options)
    if request.xhr?
      head :ok, location: controller.url_for(options)
    else
      controller.redirect_to(options)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end
  #
  # def new
  #   @user = User.new
  # end
  #
  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     log_in @user
  #     flash[:success] = "Welcome to the Note Book App!"
  #     redirect_to @user
  #   else
  #     render 'new'
  #   end
  # end
  #
  # def import_from_quick_connect
  #   ImportWizard::ImportData.new(:quick_connect_api, session).import_data
  # end
  #
  # private
  #
  #   def user_params
  #     params.require(:user).permit(:name, :email, :company, :password,
  #                                  :password_confirmation)
  #   end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_bar
    content_tag(:ul, class: "nav navbar-nav") do
      yield
    end
  end

  def nav_link(text, path)
    options = current_page?(path) ? { class: "active" } : {}
    content_tag(:li, options) do
      link_to text, path
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/close_and_redirect.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @msg %></title>
</head>
<body>
<h3><%= @msg %></h3>

<script>
setTimeout(function(){
    if(window.opener == null){
      window.location = '<%= @url %>';
    }else{
      window.opener.location = '<%= @url %>';
      window.close();
    }
}, 100);
</script>
</body>
</html>

app/views/visitors/index.html.erb
<div class="row">

  <div class="col-sm-9">
		<div class="container">
		    <div class="row col-md-11 col-md-offset-0 custyle">
		    <table class="table table-striped custab">
		    <thead>
					<% if user_signed_in?%>
					  <% unless session[:token] %>
						<ipp:connectToIntuit></ipp:connectToIntuit>
						<%else%>
					    <div>
					      <%= link_to 'Disconnect from QuickBooks', disconnect_quickbooks_path, data: { confirm: 'Are you sure you want to disconnect?' } %>
					    </div>
					  <% end %>
					  <% if notice %>
					    <div style="padding: 10px;background: gainsboro;font-weight: 900;width: 50%;"><%= notice %></div>
					  <% end %>


					  <script type="text/javascript" src="https://appcenter.intuit.com/Content/IA/intuit.ipp.anywhere.js"></script>
					  <!-- configure the Intuit object: 'grantUrl' is a URL in your application which kicks off the flow, see below -->
					  <script>
					      intuit.ipp.anywhere.setup({menuProxy: '/path/to/blue-dot', grantUrl: '<%= authenticate_quickbooks_url %>'});
					  // <% if user_signed_in? && !session[:token] %>
					  //     intuit.ipp.anywhere.directConnectToIntuit();
					  // <% end %>
					  </script>
						<%else%>
		
						<%end%>
				<%= link_to '+  Add new Customers', root_path, method: :get,  class: "btn btn-primary btn-xs pull-right"%>
				
		        <tr>
		            <th>ID</th>
		            <th>Title</th>
		            <th data-hide="phone,tablet">Type</th>
		            <th >Status</th>
		            <th data-hide="phone,tablet">Reporter Type</th>
		            <th>Views</th>
		            <th class="text-center">Action</th>
		        </tr>
		    </thead>
		            <tr>
		                <td>1</td>
		                <td>News</td>
		                <td>Breaking</td>
		                <td>Published</td>
		                <td>Citizen</td>
		                <td>15000</td>
		                <td class="text-center"><a class='btn btn-info btn-xs' href="#"><span class="glyphicon glyphicon-edit"></span> Edit</a> <a href="#" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Del</a></td>
		            </tr>
		    </table>
		    </div>
		</div>
</div>
</div>