config/routes.rb
Rails.application.routes.draw do
  
  resources :products
  resources :payments
  resources :invoices

  devise_for :users
  resources :users
  root to: 'visitors#index'
  resources :customers
  resources :quickbooks do
    collection do
      get :authenticate
      get :oauth_callback
      get :disconnect
    end
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :customer
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  
  belongs_to :user
  
  has_one :shipping_address, class_name: 'Address', dependent: :destroy
  has_one :billing_address, class_name: 'Address', dependent: :destroy
  
  has_many :invoices, dependent: :destroy
  has_many :payments, dependent: :destroy
  
  accepts_nested_attributes_for :shipping_address, allow_destroy: true
  accepts_nested_attributes_for :billing_address, allow_destroy: true
  accepts_nested_attributes_for :payments, allow_destroy: true
  accepts_nested_attributes_for :invoices, allow_destroy: true
  
end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  
  belongs_to :customer
  
  has_many :payments
  has_many :sales_line_item_detail, dependent: :destroy
  has_many :products, through: :sales_line_item_details
  
  has_one :transacion, as: :transactionable
  has_one :sub_total_line_item_detail, dependent: :destroy
  has_one :tax_line_item_detail, dependent: :destroy
  has_one :discount_line_item_detail, dependent: :destroy
  
  accepts_nested_attributes_for :sales_line_item_detail, allow_destroy: true
  accepts_nested_attributes_for :sub_total_line_item_detail, allow_destroy: true
  accepts_nested_attributes_for :tax_line_item_detail, allow_destroy: true
  accepts_nested_attributes_for :discount_line_item_detail, allow_destroy: true
  
  before_update :update_attributes
  before_save :update_attributes
  after_save :update_attributes
  after_update :update_attributes
  after_initialize :update_attributes
  
  def update_attributes
    t_price = tot_price - discount_price
   # t_price - () (tax_precent * t_price)
  end
  
  def tot_price
    sales_line_item_detail.to_a.sum(&:total_price) 
  end
  
  def tax_precent
    tax_line_item_detail.tax_precent / 100
  end
  
  def discount_percent
    discount_line_item_detail.discount_percentage / 100
  end
  
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  has_one :transacion, as: :transactionable
  belongs_to :invoice
  belongs_to :customer  
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :product_category
  
  has_many :sales_line_item_details
  has_many :invoices, through: :sales_line_item_details
end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  has_many :products
end

app/models/sales_line_item_detail.rb
class SalesLineItemDetail < ActiveRecord::Base
  belongs_to :product
  belongs_to :invoice
end

app/models/tax_line_item_detail.rb
class TaxLineItemDetail < ActiveRecord::Base
  belongs_to :invoice
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :transactionable, polymorphic: true
  belongs_to :user
  belongs_to :transaction_category
end

app/models/transaction_category.rb
class TransactionCategory < ActiveRecord::Base
  has_many :transactions
  accepts_nested_attributes_for :transactions, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :customers
  has_many :transactions
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable
  
  def self.find_for_open_id(access_token, signed_in_resource=nil)
    data = access_token.info
    if user = User.where(:email => data["email"]).first
      user
    else
      User.create!(:email => data["email"], :password => Devise.friendly_token[0,20])
    end
  end
end

app/controllers/modal_responder.rb
class ModalResponder < ActionController::Responder
  cattr_accessor :modal_layout
  self.modal_layout = 'modal'

  def render(*args)
    options = args.extract_options!
    if request.xhr?
      options.merge! layout: modal_layout
    end
    controller.render *args, options
  end

  def default_render(*args)
    render(*args)
  end

  def redirect_to(options)
    if request.xhr?
      head :ok, location: controller.url_for(options)
    else
      controller.redirect_to(options)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end
  #
  # def new
  #   @user = User.new
  # end
  #
  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     log_in @user
  #     flash[:success] = "Welcome to the Note Book App!"
  #     redirect_to @user
  #   else
  #     render 'new'
  #   end
  # end
  #
  # def import_from_quick_connect
  #   ImportWizard::ImportData.new(:quick_connect_api, session).import_data
  # end
  #
  # private
  #
  #   def user_params
  #     params.require(:user).permit(:name, :email, :company, :password,
  #                                  :password_confirmation)
  #   end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_bar
    content_tag(:ul, class: "nav navbar-nav") do
      yield
    end
  end

  def nav_link(text, path)
    options = current_page?(path) ? { class: "active" } : {}
    content_tag(:li, options) do
      link_to text, path
    end
  end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	# Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Note Book", '#', id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
              <li><%= link_to "Profile", '#' %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li>
                <%= link_to "Log out", '#', method: "delete" %>
              </li>
          </li>
        <% else %>
          <li><%= link_to "Log in", '#' %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_leftnav.html.erb
  <div class="col-sm-2">
    <div class="sidebar-nav">
      <div class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <span class="visible-xs navbar-brand">Sidebar menu</span>
        </div>
        <div class="navbar-collapse collapse sidebar-navbar-collapse">
					
					<%= nav_bar do %>
					  <%= nav_link 'Customers', customers_path %>
					  <%= nav_link 'Invoices', invoices_path %>
					  <%= nav_link 'Users', root_path %>
					<% end %>
					
					
					
					
					
          <!-- <ul class="nav navbar-nav">
            <li class="active"><a href="#">Customers</a></li>
            <li><a href="#">Products/Services</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Transactions <b class="caret"></b></a>
              <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu">
                <li><a href="#">Invoices</a></li>
                <li><a href="#">Payments</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">link</a></li>
              </ul>
            </li>
            <li><a href="#"> Quick Connect</a></li>
            <li><a href="#">Reports <span class="badge">10</span></a></li>
          </ul> -->
        </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Note Book App', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application1.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NoteBookApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= render 'layouts/navigation' %>
<%= render 'layouts/leftnav' %>
<div id="modal-holder"></div>
<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/layouts/modal.html.erb
<div class="modal" id="mainModal" tabindex="-1" role="dialog" aria-labelledby="mainModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="mainModalLabel">
          <%= yield :title if content_for? :title %>&nbsp;
        </h4>
      </div>

      <%= yield %>
    </div>
  </div>
</div>